### ISSUE TITLE
doc to vec error in Sentiment140_W2V_Pipeline.py

### ISSUE THREAD

**Issue by Sandy4321** [Lab41/sunny-side-up#83]
at line
        model.train(np.random.permutation(labeled_sent))

in code
    for epoch in xrange(epoch_num):
        logging.info("Epoch %s..." % epoch)
        # Temporarily sets logging level to show only if its at least WARNING
        # This prevents model.train from overloading the log
        logging.getLogger().setLevel(logging.WARN)
        # Numpy random permutation method shuffles data in place 
        # Shuffling improves the accuracy of the model
        model.train(np.random.permutation(labeled_sent))
        logging.getLogger().setLevel(logging.INFO)

error massage is

File "C:\Anaconda\Lib\threading.py", line 774, in __bootstrap
  self.__bootstrap_inner()
File "C:\Anaconda\Lib\threading.py", line 801, in __bootstrap_inner
  self.run()
File "C:\Anaconda\Lib\threading.py", line 754, in run
  self.__target(*self.__args, **self.__kwargs)
File "C:\Anaconda\Lib\site-packages\gensim\models\word2vec.py", line 701, in worker_loop
  if not worker_one_job(job, init):
File "C:\Anaconda\Lib\site-packages\gensim\models\word2vec.py", line 692, in worker_one_job
  tally, raw_tally = self._do_train_job(items, alpha, inits)
File "C:\Anaconda\Lib\site-packages\gensim\models\doc2vec.py", line 638, in _do_train_job
  indexed_doctags = self.docvecs.indexed_doctags(doc.tags)

AttributeError: 'numpy.ndarray' object has no attribute 'tags'

my check resuts
doc.tags
Traceback (most recent call last):
  Debug Probe, prompt 14, line 1
AttributeError: 'numpy.ndarray' object has no attribute 'tags'

thanks
I use windows pc

by the way is word2vec or doc2vec methos??

**Comment by mikefreed** [comment]
I am out of the office until 03/14/2016.

I am on leave until 3/14.  I will get back to you when I can.

Best,

Mike


Note: This is an automated response to your message  "[sunny-side-up] doc
to vec error in Sentiment140_W2V_Pipeline.py (#83)" sent on 3/7/2016
8:51:18 PM.

This is the only notification you will receive while this person is away.

**Comment by kfoss** [comment]
@Sandy4321 We're using Word2Vec methods.  The broader issue is similar to #80, where your best bet is to run everything within the project's Docker containers. The project has several dependencies, including CUDA, Keras, Neon, Gensim, etc.  The Docker containers encapsulate everything you need so you're guaranteed to run the same/correct environment we used to build the project.

For this issue, you'll want to build and run ```frameworks/docker/sentiment-ml``` since that contains all the necessary NLP (including gensim) libraries. Within that folder, the accompanying ```1-build.sh``` and ```2-run.sh``` scripts will build and run the containers.

**Comment by Sandy4321** [comment]
Thanks, but I never used Docket, may recommend some link for docker
tutorials
